services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./proxy_params:/etc/nginx/proxy_params
    depends_on:
      - backend
      - frontend
    networks:
      - mn-net
      - services
    container_name: merenib-nginx

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    restart: always
    networks:
      - mn-net
    expose:
      - 8080
    container_name: merenib-backend
  
  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    restart: always
    networks:
      - mn-net
    expose:
      - 3000
    container_name: merenib-frontend

networks:
  mn-net:
    driver: bridge
    internal: true
  services:
    external: true
    name: services